name: sharu_diary
description: Cute, minimal offline diary app with a pastel aesthetic.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  file_selector: ^0.9.4
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  record: ^6.1.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
